const styles = `
<style>
    grepo-icon {
        display: block;
        margin: 0 5px 0 5px;
        float: left;
        width: 22px;
        height: 23px;
        cursor: pointer;
    }
</style>`;
$('head').append(styles);

class IconButton extends HTMLElement {
	constructor() {
		super();

		//
		console.log($(this));
	}

	connectedCallback() {
		const type = this.getAttribute('type');
		console.log(type);
		let bg, width;

		switch (type) {
			case 'island':
				bg =
					'url(https://gpit.innogamescdn.com/images/game/autogenerated/common/bbcodes/bbcodes_6e4f630.png) no-repeat -405px -5px';
				break;
			case 'message':
				bg =
					'url(https://gpit.innogamescdn.com/images/game/button/write_message.png) no-repeat';
				width = '26px';
				break;
		}

		if (width) {
			this.style.width = width;
		}
		this.style.background = bg;

		$(this).mousePopup(new MousePopup(this.getAttribute('type')));

		// this.appendChild(linkElement);
	}
}

uw.customElements.define('grepo-icon', IconButton);
